### ISSUE TITLE
如何在RN的可滚动组件内设置一个禁止滚动的区域。（How to stopPropagation touch event ）

### ISSUE THREAD

**Issue by zgatrying** [zgatrying/react-native-practices#25]
需求：为了优化ScrollView或ViewPagerAndroid 组件下Slider组件的操作体验，需要利用PanResponder设置一块禁止滚动的区域。

问题描述：在View组件范围内，ViewPagerAndroid组件偶尔还是能够触发onPageScroll事件

示例代码
```js
//main.js
<ViewPagerAndroid onPageScroll={() => console.log('我执行了')}>
        <View>
        	<View {…stopPropagation()}><Slider/></View>
        </View>
        <View>
        	<View {…stopPropagation()}><Slider/></View>
        </View>
</ViewPagerAndroid>
```

```js
//utils.js
import { PanResponder } from "react-native";

function generateSimplePanresponder() {
  return PanResponder.create({
    onPanResponderTerminationRequest() {
      //不起作用
      return false
    },
    onStartShouldSetPanResponder: () => true,
    onMoveShouldSetPanResponder: () => true,
    onShouldBlockNativeResponder: () => true,
    onPanResponderGrant: () => {
      console.log('事件开始')
    },
    onPanResponderStart: () => {
      console.log('事件进行中')
    },
    onPanResponderRelease: () => {
      console.log('事件Release')
    },
    onPanResponderEnd: () => {
      console.log('事件End')
    },
    onPanResponderTerminate() {
      console.log('——————————————————————你的Touch事件被其他组件劫持了——————————————————')
    }
  }).panHandlers;
}

const stopPropagation = generateSimplePanresponder

export default stopPropagation
```

异常时控制台打印的内容：
```
事件开始
事件进行中
'事件End
——————————————————————你的Touch事件被其他组件劫持了——————————————————//onPageScroll事件触发
```
现象说明：ViewPagerAndroid组件偶尔会成为响应者，导致页面能够左右滑动。此时会发现子组件的onPanResponderTerminate回调被执行，说明被异常终止，ViewPagerAndroid组件成为新的响应者。

疑问：子组件设置了PanResponder注册成为触摸事件的响应者，按照RN的捕获、冒泡机制，应由子组件而不是ViewPagerAndroid组件成为触摸事件的响应者。

**Comment by zgatrying** [comment]
已知情报：ScrollView组件与FlatList等可滑动的组件与ViewPagerAndroid组件类似，都会出现以上情况。

相关issues: 

1. [Cannot prevent ViewPagerAndroid from being the responder when using PanResponder on its Parent](https://github.com/facebook/react-native/issues/18808)
2. [Scrollview PanResponder](https://github.com/facebook/react-native/issues/9545)

**Comment by zgatrying** [comment]
上述问题常见的解决方案是在其他组件接管触摸操作时，禁用父级组件（ViewPagerAndroid或ScrollView）的滚动，即设置scrollEnable为false，触摸事件结束时重新设为true。

- [React Native通过修改ScrollableTabView和ViewPager来解决左右滑动冲突的问题](https://blog.csdn.net/sinat_17775997/article/details/71424395)
- [react-native-scrollable-tab-view解决Android 左右切换和下拉刷新的手势冲突问题](https://blog.csdn.net/weixin_34365417/article/details/86915309)

实践了一番，禁用是禁用了，却是滑动了一段距离才被禁用的（更新state有延迟，先触发了ViewPagerAndroid或ScrollView的滚动事件了）

直接通过ref的方式调用`setNativeProps({scrollEnable: false})`同样会出现滚动一段距离后才会禁用滚动的情况。

**Comment by zgatrying** [comment]
已知的情报：PanResponder 手势监视器中的onPanResponderTerminationRequest 回调表示监视器被要求终止，返回false表示不同意终止，或者不处理。很悲剧的是，这个回调根本不起作用~！

**Comment by zgatrying** [comment]
其他可参考的情报：

- [React Native通过修改ScrollableTabView和ViewPager来解决左右滑动冲突的问题](https://blog.csdn.net/sinat_17775997/article/details/71424395)
- [react-native-scrollable-tab-view解决Android 左右切换和下拉刷新的手势冲突问题](https://blog.csdn.net/weixin_34365417/article/details/86915309)

**Comment by zgatrying** [comment]
一位ReactNative contributor提供的情报：

Ideally, once something gets the responder, it can prevent others from responding by setting onPanResponderTerminationRequest: () => false,

However, we often have troubles while interacting with touch interactions happening on the main thread, like the iOS slider, or any scroll views. The problem is that javascript cannot immediately reject the responsiveness of the native event, because the main thread must synchronously decide if JS or the scroll view should become responder, and JS can only respond asynchronously.

This is a difficult problem to solve, and is something we have been thinking about for a while. cc @vjeux @sahrens @jordwalke @lelandrichardson. This could be solved in a similar way as @kmagiera is moving animations to the UI thread. Basically we construct and serialize some logic such that these immediate operations can be resolved without waiting for the JS thread.

**Comment by zgatrying** [comment]
[ericvicenti](https://github.com/ericvicenti)在issue[How to stopPropagation touch event](https://github.com/facebook/react-native/issues/1046)的说明：

Ideally, once something gets the responder, it can prevent others from responding by setting onPanResponderTerminationRequest: () => false,

However, we often have troubles while interacting with touch interactions happening on the main thread, like the iOS slider, or any scroll views. The problem is that javascript cannot immediately reject the responsiveness of the native event, because the main thread must synchronously decide if JS or the scroll view should become responder, and JS can only respond asynchronously.

This is a difficult problem to solve, and is something we have been thinking about for a while. This could be solved in a similar way as @kmagiera is moving animations to the UI thread. Basically we construct and serialize some logic such that these immediate operations can be resolved without waiting for the JS thread.

理想情况下，一旦某个东西获得响应器，它可以通过设置onPanResponderTerminationRequest: () => false来阻止其他人响应，

然而，我们在与发生在主线程上的触摸交互交互(如iOS滑块或任何滚动视图)交互时，经常会遇到问题。**问题是javascript不能立即拒绝本地事件的响应，因为主线程必须同步决定JS或滚动视图是否应该成为响应器，而JS只能异步响应。**

这是一个很难解决的问题，也是我们一直在思考的问题。这可以用与@kmagiera将动画移动到UI线程类似的方法解决。基本上，我们构造并序列化一些逻辑，这样就可以在不等待JS线程的情况下解决这些即时操作。

**Comment by zgatrying** [comment]
根据ericvicenti建议的插件，使用[react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler)实现了在滚动组件内部设置禁止滚动区域的效果。

example
```js
import React, { Component } from 'react';
import { StyleSheet, Text, View, Platform } from 'react-native';

import {
  ViewPagerAndroid,
  DrawerLayoutAndroid,
  PanGestureHandler,
  Slider
} from 'react-native-gesture-handler';

const Page = ({ backgroundColor, text }) =>
  <View style={[styles.page, { backgroundColor }]}>
    <PanGestureHandler
      onGestureEvent={() => console.log('disable')}
    >
      <View 
      style={{
        width: 200,
        height: 200,
        backgroundColor: '#f00',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
        <Slider
          style={{width: 200, marginBottom: 60}}
          value={0}
          minimumValue={0}
          maximumValue={100}
        />
        <Text style={styles.pageText}>
          {text}
        </Text>
      </View>
    </PanGestureHandler>
  </View>;

export default class Example extends Component {
  render() {
    if (Platform.OS !== 'android') {
      return (
        <Text>Sorry, this is a demo of android-only native components</Text>
      );
    }
    const navigationView = (
      <View style={{ flex: 1, backgroundColor: '#fff' }}>
        <Text style={{ margin: 10, fontSize: 15, textAlign: 'left' }}>
          I'm in the Drawer!
        </Text>
      </View>
    );
    return (
      <ViewPagerAndroid 
        style={styles.container}
      >
        <View>
          <DrawerLayoutAndroid
            drawerWidth={200}
            drawerPosition={DrawerLayoutAndroid.positions.Left}
            renderNavigationView={() => navigationView}>
            <Page backgroundColor="gray" text="First 🙈" />
          </DrawerLayoutAndroid>
        </View>
        <Page backgroundColor="yellow" text="Second 🙉" />
        <Page backgroundColor="blue" text="Third 🙊" />
        <View>
          <DrawerLayoutAndroid
            drawerWidth={200}
            drawerPosition={DrawerLayoutAndroid.positions.Right}
            renderNavigationView={() => navigationView}>
            <Page backgroundColor="blue" text="Fourth 😎" />
          </DrawerLayoutAndroid>
        </View>
      </ViewPagerAndroid>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'ios' ? 20 : 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  page: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageText: {
    fontSize: 21,
    color: 'white',
  },
});
```

**Comment by zgatrying** [comment]
RN手势工作流：
![RN手势工作流](https://user-images.githubusercontent.com/18207997/58789265-5387e080-8620-11e9-82eb-2c25ef532227.png)

修正：

JS：JS Code

**Comment by chenyulun** [comment]
nice, you are pretty great
